services:
  backend:
    container_name: backend
    command: 'uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload'
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - '8080:8080'
    environment:
      DB_HOST: db
      DB_USER: master
      DB_PASSWORD: 'strong_password'
      DB_NAME: phenix_mysql
    volumes:
      - ./backend/app:/backend/app
    depends_on:
      - db
    restart: always
    networks:
      - phenix
  ampl:
    container_name: ampl
    command: 'uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload'
    build: 
      context: ./backend
      dockerfile: Dockerfile.ampl
    ports:
      - '8000:8000'
    volumes:
      - ./backend/ampl_app:/ampl/app
    restart: always
    networks:
      - phenix
  db:
    container_name: database
    image: 'mysql:8.0'
    environment:
      MYSQL_DATABASE: phenix_mysql
      MYSQL_ROOT_PASSWORD: 'strong_password'
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    networks:
      - phenix
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - '80:80'
    restart: always
    networks:
      - phenix
networks:
  phenix:
    driver: bridge
