services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - '8080:8080'
    environment:
      DB_HOST: db
      DB_USER: master
      DB_PASSWORD: 'strong_password'
      DB_NAME: phenix_mysql
    depends_on:
      - db
    restart: always
    networks:
      - phenix
  db:
    container_name: database
    image: 'mysql:8.0'
    environment:
      MYSQL_DATABASE: phenix_mysql
      MYSQL_ROOT_PASSWORD: 'strong_password'
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    networks:
      - phenix
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - '80:80'
    restart: always
    networks:
      - phenix
networks:
  phenix:
    driver: bridge
