version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    environment:
      - DB_HOST: db
      - DB_USER: master
      - DB_PASSOWRD: "strong_password"
      - DB_NAME: phenix_mysql
    depends_on:
      - db
    networks:
      phenix:
        ipv4_address: "10.56.1.1"
  db:
    image: 'mysql:8.0'
    environment:
      - DB_NAME: phenix_mysql
      - DB_ROOT_PASSWORD: "strong_password"
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      phenix:
        ipv4_address: "10.56.1.2"
  frontend:
  networks:
    phenix:
      ipv4_address: "10.56.1.3"

networks:
  phenix:
    ipam:
      driver: default
      config:
        - subnet: "10.56.1.0/24"