services:
  backend:
    container_name: backend
    command: 'uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload'
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - '8080:8080'
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: 'strong'
      DB_NAME: phenix_mysql
    volumes:
      - ./backend/app:/backend/app
    depends_on:
      - db
    restart: always
    networks:
      - phenix
  ampl:
    container_name: ampl
    command: 'uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload'
    build:
      context: ./backend
      dockerfile: Dockerfile.ampl
    volumes:
      - ./backend/ampl_app:/ampl/app
    restart: always
    networks:
      - phenix
  db:
    container_name: database
    build:
      context: ./database
      dockerfile: Dockerfile.database
    environment:
      MYSQL_DATABASE: phenix_mysql
      MYSQL_ROOT_PASSWORD: 'strong'
    volumes:
      - ./database/db_data:/var/lib/mysql
    restart: always
    networks:
      - phenix
  db_adminer:
    container_name: db_adminer
    image: adminer
    restart: always
    ports:
      - '8081:8080'
    networks:
      - phenix
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - '8085:8085'
    restart: always
    networks:
      - phenix
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./frontend/app/dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - phenix
networks:
  phenix:
    driver: bridge
