FROM python:3

# Set the workdir 
WORKDIR /backend

# Copy the application code into the container
COPY ./app/requirements.txt /backend/requirements.txt

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

COPY ./app /backend/app

# docs
EXPOSE 8080

# Start the Fast API
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8080", "--reload"]