FROM python:3.9-slim-bullseye

# Copy the application code into the container
COPY . .

# Set the workdir 
WORKDIR /app

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt


# Start the Fast API
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]